version: '3.8'

services:
  sales-rag-bot:
    build: .
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - DEBUG=false
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./sales_rag.db:/app/sales_rag.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 